@baseUrl = http://localhost:3001/api/persons

GET {{baseUrl}}

###

POST {{baseUrl}} 
Content-Type: application/json

{
  "name": "cos",
  "number": "000000000"
}

###

GET {{baseUrl}}/65da4f4d8b29cc54801b9492

###

DELETE {{baseUrl}}/65da4f4d8b29cc54801b9492